name: Build PR

on:
  pull_request:

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/docusaurus-dev-container"

jobs:
  generate_infos:
    uses: fullstack-devops/git-workflows/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build github-actions-runner:base
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}
